version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8060:8060
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=shelter
    

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./pkg/clinic-api/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:1234@db:5432/shelter?sslmode=disable", "up"]
    depends_on:
      - db

volumes:
  pgdata: